"""
project_paths.py — Single source of truth for all workspace file paths.

All backend code should import path helpers from here instead of
constructing paths inline. This makes folder structure changes a
one-file edit.

Workspace layout (per project):
  workspace/{project}/
    memory/                 ← LLM context files (auto-generated by /memory)
      claude/
        CLAUDE.md           ← copied to code_dir/CLAUDE.md
        features/           ← per-feature snapshots
        hooks/              ← hook scripts
      cursor/rules.md       ← compact, copied to code_dir/.cursorrules
      copilot/instructions.md ← compact (= cursor/rules.md), → code_dir/.github/copilot-instructions.md
      api/system_prompt.md  ← compact, shared by all API providers (Claude/OpenAI/Gemini/Grok/DeepSeek)
      context.md            ← injected by aicli CLI into ALL providers
      code.md               ← directory tree + hotspots + file coupling
      GEMINI.md             ← full (= CLAUDE.md), copied to code_dir/GEMINI.md
      AGENTS.md             ← full (= CLAUDE.md), copied to code_dir/AGENTS.md
      memory.yaml           ← maps all CLI tools + APIs to their context files
      _mcp.json             ← Claude Code / Cursor MCP config template
      _codex.toml           ← Codex CLI MCP config template
      _opencode.json        ← OpenCode config template
    state/                  ← runtime state files
      project_state.json
      session_tags.json
      session_phases.json
      dev_runtime_state.json
      CONTEXT.md
      .git_token
    history/                ← append-only history logs
      history.jsonl         ← conversation history (all prompts)
      commit_log.jsonl      ← git commit log
      history_*.jsonl       ← rotated history archives
    sessions/               ← per-session JSON files (LLM message continuity)
    pipelines/              ← pipeline definitions, prompts, and run results
      samples/              ← sample pipeline YAML files
      prompts/              ← pipeline prompt files
      runs/                 ← pipeline run result JSONs
    documents/              ← user-managed docs (use cases, references)
"""
from __future__ import annotations

from pathlib import Path

from core.config import settings


# ── Project root ──────────────────────────────────────────────────────────────

def proj_dir(project: str) -> Path:
    return Path(settings.workspace_dir) / project


# ── Top-level dirs ────────────────────────────────────────────────────────────

def memory_dir(project: str) -> Path:
    """Root for all LLM context files."""
    return proj_dir(project) / "memory"


def sessions_dir(project: str) -> Path:
    """Per-session JSON files."""
    return proj_dir(project) / "sessions"


def state_dir(project: str) -> Path:
    """Runtime state files (tags, project_state, context…)."""
    return proj_dir(project) / "state"


def pipelines_dir(project: str) -> Path:
    """Pipeline definitions, prompts, samples, and run results."""
    return proj_dir(project) / "pipelines"


def runs_dir(project: str) -> Path:
    """Pipeline run result files."""
    return pipelines_dir(project) / "runs"


# ── Backward-compat — removed folders ────────────────────────────────────────

def logs_dir(project: str) -> Path:
    """Deprecated: logs/ folder removed. Returns history_dir() for archive scans."""
    return history_dir(project)


def pipeline_logs_dir(project: str) -> Path:
    """Deprecated: logs/pipeline/ removed. Returns pipelines/runs/."""
    return runs_dir(project)


def workflows_dir(project: str) -> Path:
    """Deprecated: renamed to pipelines_dir()."""
    return pipelines_dir(project)


# ── memory/ subdirs ───────────────────────────────────────────────────────────

def claude_dir(project: str) -> Path:
    return memory_dir(project) / "claude"


def cursor_dir(project: str) -> Path:
    return memory_dir(project) / "cursor"


def copilot_dir(project: str) -> Path:
    return memory_dir(project) / "copilot"


def openai_dir(project: str) -> Path:
    return memory_dir(project) / "openai"


def gemini_dir(project: str) -> Path:
    return memory_dir(project) / "gemini"


def api_dir(project: str) -> Path:
    """Shared API system prompt directory (all LLM API providers)."""
    return memory_dir(project) / "api"


# ── Named file paths ──────────────────────────────────────────────────────────

def claude_md_path(project: str) -> Path:
    return claude_dir(project) / "CLAUDE.md"


def cursor_rules_path(project: str) -> Path:
    return cursor_dir(project) / "rules.md"


def copilot_instructions_path(project: str) -> Path:
    return copilot_dir(project) / "instructions.md"


def openai_compact_path(project: str) -> Path:
    return openai_dir(project) / "compact.md"


def openai_full_path(project: str) -> Path:
    return openai_dir(project) / "full.md"


def gemini_context_path(project: str) -> Path:
    return gemini_dir(project) / "context.md"


def api_system_prompt_path(project: str) -> Path:
    """Shared compact system prompt for all API providers."""
    return api_dir(project) / "system_prompt.md"


def aicli_context_path(project: str) -> Path:
    """Shared context injected by aicli CLI into ALL providers."""
    return memory_dir(project) / "context.md"


def code_md_path(project: str) -> Path:
    return memory_dir(project) / "code.md"


def project_md_path(project: str) -> Path:
    """Living project documentation (PROJECT.md), stored in memory/."""
    return memory_dir(project) / "PROJECT.md"


# ── state/ files ─────────────────────────────────────────────────────────────

def project_state_path(project: str) -> Path:
    return state_dir(project) / "project_state.json"


def session_tags_path(project: str) -> Path:
    return state_dir(project) / "session_tags.json"


def session_phases_path(project: str) -> Path:
    return state_dir(project) / "session_phases.json"


def dev_runtime_state_path(project: str) -> Path:
    return state_dir(project) / "dev_runtime_state.json"


def history_dir(project: str) -> Path:
    """Append-only history logs (history.jsonl, commit_log.jsonl, rotated archives)."""
    return proj_dir(project) / "history"


def history_path(project: str) -> Path:
    return history_dir(project) / "history.jsonl"


def commit_log_path(project: str) -> Path:
    return history_dir(project) / "commit_log.jsonl"


def context_md_path(project: str) -> Path:
    return state_dir(project) / "CONTEXT.md"


def git_token_path(project: str) -> Path:
    return state_dir(project) / ".git_token"


# ── Backward-compat aliases (remove after full migration) ────────────────────

def cli_dir(project: str) -> Path:
    """Deprecated: use memory_dir()."""
    return memory_dir(project)


# ── Log cleanup ───────────────────────────────────────────────────────────────

def cleanup_project_logs(project: str, pipeline_days: int = 14, history_days: int = 30) -> int:
    """Delete stale per-project log files.

    - logs/pipeline/*.log  older than pipeline_days
    - logs/history_*.jsonl older than history_days

    Returns count of deleted files.
    """
    import time
    deleted = 0
    now = time.time()

    pipe_dir = pipeline_logs_dir(project)
    if pipe_dir.exists():
        cutoff = now - pipeline_days * 86400
        for f in pipe_dir.glob("*.log"):
            try:
                if f.stat().st_mtime < cutoff:
                    f.unlink()
                    deleted += 1
            except OSError:
                pass

    hist_d = history_dir(project)
    if hist_d.exists():
        cutoff = now - history_days * 86400
        for f in hist_d.glob("history_*.jsonl"):
            try:
                if f.stat().st_mtime < cutoff:
                    f.unlink()
                    deleted += 1
            except OSError:
                pass

    return deleted


# ── Directory creation helpers ────────────────────────────────────────────────

def ensure_project_dirs(project: str) -> None:
    """Create all required project directories if they don't exist."""
    for d in [
        memory_dir(project),
        claude_dir(project),
        claude_dir(project) / "features",
        cursor_dir(project),
        copilot_dir(project),
        api_dir(project),
        sessions_dir(project),
        state_dir(project),
        history_dir(project),
        pipelines_dir(project),
        runs_dir(project),
    ]:
        d.mkdir(parents=True, exist_ok=True)
