# aicli — AI Coding Rules
> Managed by aicli. Run `/memory` to refresh. Generated: 2026-04-27 00:40 UTC

# aicli — Shared AI Memory Platform

_Last updated: 2026-04-27_

> **How this file works**
> - Sections marked `<!-- user-managed -->` are yours to edit freely — they feed directly into CLAUDE.md.
> - Sections marked `<!-- auto-updated by /memory -->` are refreshed automatically when you run `/memory`.
>   You can still edit them; `/memory` will merge its output in without discarding your additions.
> - Run `/memory` to regenerate CLAUDE.md, cursor rules, and all LLM prompt files from this docum

## Tech Stack

- **cli**: Python 3.12 + prompt_toolkit + rich
- **backend**: FastAPI + uvicorn + python-jose + bcrypt + psycopg2
- **frontend**: Vanilla JS + Electron + Vite
- **ui_components**: xterm.js + Monaco editor + Cytoscape.js
- **storage**: PostgreSQL 15+ with pgvector (1536-dim, text-embedding-3-small)
- **authentication**: JWT (python-jose + bcrypt) + DEV_MODE
- **llm_providers**: Claude (Haiku/Sonnet/Opus) + OpenAI (GPT-4/mini) + DeepSeek + Gemini + Grok
- **workflow_engine**: Async DAG executor (asyncio.gather) + YAML config + per-node retry
- **memory_synthesis**: Claude Haiku dual-layer + 11 output files + token limits (project.yaml)
- **chunking**: Smart: per-class/function (Python/JS/TS) + per-section (Markdown) + per-file (diffs)
- **mcp**: Stdio MCP server with rewired work item tools
- **deployment_backend**: Railway (Dockerfile + railway.toml)
- **deployment_desktop**: Electron-builder (Mac dmg, Windows nsis, Linux AppImage+deb)
- **database_migrations**: PostgreSQL 15+ with m001-m080 framework; m080 adds 4-agent pipeline columns
- **config_management**: project.yaml (memory limits, hotspot_threshold) + memory.yaml (canonical file mapping)

## Key Decisions

- Workspace structure: aicli/cli/{claude,mcp}/ for hooks/configs; aicli/pipelines/{prompts,samples}/ for workflows; aicli/documents/ for project files; aicli/state/ for runtime state. No .ai/ or _system/ folders.
- Memory files (PROJECT.md, CODE.md, CLAUDE.md, cursorrules.md, recent_work.md) generated by /memory endpoint from project_state.json + database; token-limited by project.yaml config block
- backend/memory/memory.yaml is canonical single source for file mapping; templates in backend/memory/templates/
- Code.md structure: public symbols (classes/methods/functions) + file coupling/hotspot tables with is_latest BOOLEAN pattern; generated from mem_mrr_commits_code table per commit
- mem_mrr_commits_code (19 columns) with is_latest BOOLEAN: replaces separate code_symbols table; updated per commit; partial index optimization
- Work Items + Use Cases: unified hierarchy via wi_parent_id; approved items trigger 4-agent pipeline (PM→Architect→Developer→Reviewer) with acceptance_criteria, implementation_plan, pipeline_status, pipeline_run_id columns (m080)
- Drag-and-drop uses document.elementFromPoint() target detection; undo as persistent toolbar button stores reverse API call closure capturing original parent_id
- JWT authentication: python-jose + bcrypt with DEV_MODE toggle; hierarchical Clients→Users→Projects
- LLM provider adapters: Claude/OpenAI/DeepSeek/Gemini/Grok as independent modules in agents/providers/ with send(prompt, system) → str contract
- All backend LLM prompts in YAML files under backend/memory/prompts/: command_memory.yaml (/memory), command_work_items.yaml (/wi), event_commit.yaml (post-commit), event_hook_context.yaml (hook synthesis)
- Embedding strategy: mem_work_items VECTOR(1536) used for /search/semantic; optional for commits/prompts
- MCP tools rewired: create_entity→POST /wi/{project}, list_work_items→GET /wi/{project}, sync_github_issues→PATCH /wi/{project}
- 4-agent pipeline for approved work items: pm_analysis, architect_plan, dev_implementation, reviewer_validation columns on mem_work_items; triggered by approved use case parent
- project_state.json generated only by /memory endpoint; drives all 11 memory file outputs; no other code path writes it
- Hotspot threshold configured via project.yaml memory.hotspot_threshold; code.md now refreshes after every commit via memory_files.py:sync_code_structure()

## Recent Context (last 5 changes)

- [2026-04-27] is there is /commit command ? Also you mention code.md is created by command_memory . it is not supposed to update file 
- [2026-04-27] why you rename the yaml to command_commit if there is no command ? this yaml manage after commit event no ?
- [2026-04-27] The current project_state stored fact like 5-layer memory architecture with /memory endpoint + LLM synthesis via Haiku o
- [2026-04-27] Again, please clear all aiCli_memory.md as it is too long and start to explain from scratch all memory mechanism.  for c
- [2026-04-27] Do the same for work_item - is well sumerrised to use cases, items types (feature, bug, taks) item score (no started- im